#!/usr/bin/env zsh

# ================================================================ #
# ZSH Base Directory
# ================================================================ #

export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
export ZSH_CONFIG_DIR="${XDG_CONFIG_HOME}/zsh"
export ZSH_DATA_DIR="${XDG_DATA_HOME}/zsh"
export ZSH_STATE_DIR="${XDG_STATE_HOME}/zsh"

# Make sure the directories exist.
mkdir -p "${ZSH_CACHE_DIR}" "${ZSH_CONFIG_DIR}" "${ZSH_DATA_DIR}" "${ZSH_STATE_DIR}"

# Load .zshrc.before if it exists.
if [ -f "${HOME}/.zshrc.before" ]; then
  source "${HOME}/.zshrc.before"
fi

# Load the zsh configuration.
source "${ZSH_CONFIG_DIR}/builtin.zsh"
source "${ZSH_CONFIG_DIR}/shell.zsh"
source "${ZSH_CONFIG_DIR}/zinit.zsh"

# Load .zshrc.after if it exists.
if [ -f "${HOME}/.zshrc.after" ]; then
  source "${HOME}/.zshrc.after"
fi
