#!/usr/bin/env zsh

# XDG
export XDG_BIN_HOME="${HOME}/.local/bin"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_RUNTIME_DIR="${HOME}/.local/runtime"
export XDG_STATE_HOME="${HOME}/.local/state"

mkdir -p ${XDG_BIN_HOME} ${XDG_CACHE_HOME} ${XDG_CONFIG_HOME} \
  ${XDG_DATA_HOME} ${XDG_RUNTIME_DIR} ${XDG_STATE_HOME}

# Zsh
export ZSH_CACHE_HOME="${XDG_CACHE_HOME}/zsh"
export ZSH_CONFIG_HOME="${XDG_CONFIG_HOME}/zsh"
export ZSH_DATA_HOME="${XDG_DATA_HOME}/zsh"
export ZSH_COMPLETIONS_HOME="${ZSH_DATA_HOME}/completions"

mkdir -p ${ZSH_CACHE_HOME} ${ZSH_CONFIG_HOME} ${ZSH_DATA_HOME} ${ZSH_COMPLETIONS_HOME}

[ -f "${HOME}/.zshrc.before" ] && source "${HOME}/.zshrc.before"
source ${ZSH_CONFIG_HOME}/shell.zsh
source ${ZSH_CONFIG_HOME}/config.zsh
source ${ZSH_CONFIG_HOME}/zinit.zsh
[ -f "${HOME}/.zshrc.after" ] && source "${HOME}/.zshrc.after"
